/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InquirycopyRouteImport } from './routes/inquiry copy'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as IndexRouteImport } from './routes/index'

const InquirycopyRoute = InquirycopyRouteImport.update({
  id: '/inquiry copy',
  path: '/inquiry copy',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/inquiry': typeof InquiryRoute
  '/inquiry copy': typeof InquirycopyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/inquiry': typeof InquiryRoute
  '/inquiry copy': typeof InquirycopyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/destinations': typeof DestinationsRoute
  '/inquiry': typeof InquiryRoute
  '/inquiry copy': typeof InquirycopyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/destinations' | '/inquiry' | '/inquiry copy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/destinations' | '/inquiry' | '/inquiry copy'
  id: '__root__' | '/' | '/destinations' | '/inquiry' | '/inquiry copy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DestinationsRoute: typeof DestinationsRoute
  InquiryRoute: typeof InquiryRoute
  InquirycopyRoute: typeof InquirycopyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inquiry copy': {
      id: '/inquiry copy'
      path: '/inquiry copy'
      fullPath: '/inquiry copy'
      preLoaderRoute: typeof InquirycopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DestinationsRoute: DestinationsRoute,
  InquiryRoute: InquiryRoute,
  InquirycopyRoute: InquirycopyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
